### ISSUE TITLE
Groovy/Gradle version requirements?

### ISSUE THREAD

**Issue by IndicatorFluid** [nebula-plugins/nebula-release-plugin#152]
It's not clear what the comparability is between versions.
I am using Gradle 4.6 which uses Groovy 2.4.12 and it seems I cannot use the latest version of the plugin:
```
Caused by: java.lang.NoSuchMethodError: org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(Ljava/lang/Iterable;Lgroovy/lang/Closure;)Ljava/util/List;
        at nebula.plugin.release.ErrorMessageFormatter.annotate(ErrorMessageFormatter.groovy:37)
        at nebula.plugin.release.ErrorMessageFormatter.format(ErrorMessageFormatter.groovy:22)
        at nebula.plugin.release.ErrorMessageFormatter$format.call(Unknown Source)
        at nebula.plugin.release.ReleasePlugin.checkStateForStage(ReleasePlugin.groovy:214)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy:154)
        at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:164)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addImperativePlugin(DefaultPluginManager.java:80)
        at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:87)
```

**Comment by chali** [comment]
Hello @IndicatorFluid. I'm not sure what version of our plugin are you using. But the latest version needs at least Gradle 5.1. However, to be sure I would recommend Gradle 5.5. We do only testing against latest Gradle release.

**Comment by IndicatorFluid** [comment]
Sure, I am just suggesting you guys should state which version of the plugin requires which version of gradle.
I've wasted a good chunk of time trying to understand why it's not working.

**Comment by chali** [comment]
It is part of the release notes. https://github.com/nebula-plugins/nebula-release-plugin/releases/tag/v9.2.0 but I agree there is an opportunity to make it clearer. Thank you for the feedback.
