### ISSUE TITLE
java.lang.AbstractMethodError with nebula.release.plugin

### ISSUE THREAD

**Issue by ankit-joinwal** [nebula-plugins/nebula-release-plugin#201]
Executing below tasks
```
clean build final --stacktrace
```

Execution Java - 1.8.222
Gradle Version: 5.2.1

Receiving error:

```
Caused by: java.lang.AbstractMethodError
16:06:06 	at org.eclipse.jgit.util.SystemReader.getJGitConfig(SystemReader.java:348)
16:06:06 	at org.eclipse.jgit.util.SystemReader.getSystemConfig(SystemReader.java:373)
16:06:06 	at org.eclipse.jgit.util.SystemReader.getUserConfig(SystemReader.java:321)
16:06:06 	at org.eclipse.jgit.internal.storage.file.FileRepository.getConfig(FileRepository.java:353)
16:06:06 	at org.eclipse.jgit.internal.storage.file.FileRepository.getConfig(FileRepository.java:1)
16:06:06 	at org.eclipse.jgit.transport.Transport.open(Transport.java:271)
16:06:06 	at org.eclipse.jgit.transport.Transport.open(Transport.java:243)
16:06:06 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:203)
16:06:06 	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:1)
16:06:06 	at java_util_concurrent_Callable$call$0.call(Unknown Source)
16:06:06 	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:61)
16:06:06 	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy)
16:06:06 	at java_util_concurrent_Callable$call.call(Unknown Source)
16:06:06 	at java_util_concurrent_Callable$call.call(Unknown Source)
16:06:06 	at org.ajoberstar.grgit.internal.OpSyntax.mapOperation(OpSyntax.groovy:20)
16:06:06 	at org.ajoberstar.grgit.internal.OpSyntax$mapOperation.callStatic(Unknown Source)
16:06:06 	at org.ajoberstar.grgit.Grgit.fetch(Grgit.groovy)
16:06:06 	at org.ajoberstar.grgit.Grgit$fetch$3.call(Unknown Source)
16:06:06 	at nebula.plugin.release.git.base.BaseReleasePlugin.prepare(BaseReleasePlugin.groovy:82)
16:06:06 	at nebula.plugin.release.git.base.BaseReleasePlugin$_addPrepareTask_closure2$_closure5.doCall(BaseReleasePlugin.groovy:57)
16:06:06 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:648)
```

**Comment by ankit-joinwal** [comment]
Fixed by upgrading to Gradle 6
