### ISSUE TITLE
Underscores in feature branch names throw an error

### ISSUE THREAD

**Issue by plumlee** [nebula-plugins/nebula-release-plugin#22]
Using this sort of branch name: `feature/readjust_releasenote_publish` throws the error below. (full output, just in case that’s valuable)

I know this isn’t a bug in your library, but rather an (intended?) omission in https://github.com/zafarkhaja/jsemver, but I’m trying to figure out why the actual branch name is being parsed once it’s clear it’s a feature branch versus a release branch, where the version might be needed? I’d think that once `feature` was detected in the branch name, then the parsing of a version should stop, unless `feature` was a valid release branch?

Would you agree that `_` should be a valid character in a branch name?

EDIT - I think what I’m really trying to ask is what’s the overall flow for parsing the branch name? At what point is it trying to extract a version, and how does that tie into the fact that I’ve already declared that this should run as devSnapshot by using `feature/` in the branch name? 

```
Cause 1: Unexpected character 'ILLEGAL(_)' at position '32', expecting '[EOL]'
	at com.github.zafarkhaja.semver.VersionParser.consumeNextCharacter(VersionParser.java:516)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:269)
	at com.github.zafarkhaja.semver.VersionParser.parseValidSemVer(VersionParser.java:195)
	at com.github.zafarkhaja.semver.Version$Builder.build(Version.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:368)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
	at org.ajoberstar.gradle.git.release.semver.SemVerStrategyState$_toVersion_closure1.doCall(SemVerStrategyState.groovy:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:235)
	at org.codehaus.groovy.runtime.dgm$614.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.ajoberstar.gradle.git.release.semver.SemVerStrategyState.toVersion(SemVerStrategyState.groovy:43)
	at org.ajoberstar.gradle.git.release.semver.SemVerStrategyState$toVersion$9.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.ajoberstar.gradle.git.release.semver.SemVerStrategy.doInfer(SemVerStrategy.groovy:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at org.ajoberstar.gradle.git.release.semver.SemVerStrategy.infer(SemVerStrategy.groovy:119)
	at org.ajoberstar.gradle.git.release.base.VersionStrategy$infer$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion.infer(ReleasePluginExtension.groovy:114)
	at org.ajoberstar.gradle.git.release.base.ReleasePluginExtension$DelayedVersion.toString(ReleasePluginExtension.groovy:120)
	at org.gradle.api.internal.artifacts.ProjectBackedModule.getVersion(ProjectBackedModule.java:38)
	at org.gradle.api.publish.maven.plugins.MavenPublishPlugin$MavenPublicationFactory.create(MavenPublishPlugin.java:176)
	at org.gradle.api.publish.maven.plugins.MavenPublishPlugin$MavenPublicationFactory.create(MavenPublishPlugin.java:162)
	at org.gradle.api.internal.DefaultPolymorphicDomainObjectContainer.doCreate(DefaultPolymorphicDomainObjectContainer.java:61)
	at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.create(AbstractPolymorphicDomainObjectContainer.java:62)
	at org.gradle.api.internal.AbstractPolymorphicDomainObjectContainer.create(AbstractPolymorphicDomainObjectContainer.java:49)
	at org.gradle.api.PolymorphicDomainObjectContainer$create.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin$1.execute(NebulaMavenPublishingPlugin.groovy:79)
	at nebula.plugin.publishing.maven.NebulaMavenPublishingPlugin$1.execute(NebulaMavenPublishingPlugin.groovy)
	at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
	at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.configureNow(ExtensionsStorage.java:183)
	at org.gradle.api.internal.plugins.ExtensionsStorage$DeferredConfigurableExtensionHolder.get(ExtensionsStorage.java:162)
	at org.gradle.api.internal.plugins.ExtensionsStorage.getByType(ExtensionsStorage.java:77)
	at org.gradle.api.internal.plugins.DefaultConvention.getByType(DefaultConvention.java:116)
	at org.gradle.api.publish.plugins.PublishingPlugin$Rules.publishing(PublishingPlugin.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.model.internal.inspect.ModelRuleInspector$MethodModelCreator.invoke(ModelRuleInspector.java:271)
	at org.gradle.model.internal.inspect.ModelRuleInspector$MethodModelCreator.create(ModelRuleInspector.java:253)
	at org.gradle.model.internal.registry.DefaultModelRegistry.doCreate(DefaultModelRegistry.java:389)
	at org.gradle.model.internal.registry.DefaultModelRegistry.createAndClose(DefaultModelRegistry.java:319)
	at org.gradle.model.internal.registry.DefaultModelRegistry.get(DefaultModelRegistry.java:315)
	at org.gradle.model.internal.registry.DefaultModelRegistry.element(DefaultModelRegistry.java:211)
	at org.gradle.model.internal.registry.DefaultModelRegistry.toInput(DefaultModelRegistry.java:430)
	at org.gradle.model.internal.registry.DefaultModelRegistry.toInputs(DefaultModelRegistry.java:422)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutation(DefaultModelRegistry.java:405)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutations(DefaultModelRegistry.java:340)
	at org.gradle.model.internal.registry.DefaultModelRegistry.close(DefaultModelRegistry.java:326)
	at org.gradle.model.internal.registry.DefaultModelRegistry.createAndClose(DefaultModelRegistry.java:320)
	at org.gradle.model.internal.registry.DefaultModelRegistry.get(DefaultModelRegistry.java:315)
	at org.gradle.model.internal.registry.DefaultModelRegistry.get(DefaultModelRegistry.java:205)
	at org.gradle.configuration.project.TaskModelRealizingConfigurationAction.execute(TaskModelRealizingConfigurationAction.java:31)
	at org.gradle.configuration.project.TaskModelRealizingConfigurationAction.execute(TaskModelRealizingConfigurationAction.java:27)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:521)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:82)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
```

**Comment by rspieldenner** [comment]
I'll take a look at some point. We certainly should allow underscores in branch names if it is our code throwing the error. If it's one of our dependencies I'll see what we can do.

**Comment by plumlee** [comment]
Thanks! I can give further debugging info as needed.

**Comment by mjalford** [comment]
The root cause is that the dependency, Java-semver (https://github.com/zafarkhaja/jsemver), is enforcing the Semantic Versioning 2.0 spec on version names.

Because the Nebula release plugin is attempting to create a version off of a branch name for development releases, we are running into a violation of the spec.  

Possible solutions:
1.  Consider the issue to be "working as designed".  Add a paragraph to the "Caveats" section of the nebula-release plugin docs so that others are not surprised.
2.  Provide an ability to configure a different version naming convention for devSnapshot that does not include branch name in the version name.
3.  Escape the characters in the branch name that are outside of those allowed by the Semantic Versioning spec.

From http://semver.org/
“9.  A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.”

**Comment by rspieldenner** [comment]
We can probably translate the underscores into dots then

**Comment by plumlee** [comment]
I’m good with using dots, or giving an option to make the branch name not be part of the version.
