### ISSUE TITLE
> Problem fetching from remote.

### ISSUE THREAD

**Issue by robertmircea** [nebula-plugins/nebula-release-plugin#40]
Hi,

I need some help to solve the issue from the subject when  running 
```./gradlew candidate```

from osx. The task failed with the following error message "Problem fetching from remote". When looking at gradle's stacktrace, I found the following error message related to authentication:

`
Caused by: org.eclipse.jgit.api.errors.TransportException: ssh://git@scm.office.xyz.intra:7999/op/springboot-playground.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:76)
`

I am using a RSA private key and when I run ```git fetch``` or other remote commands at shell prompt everything works smoothly.

Any hints on how to get past this issue?

**Comment by rspieldenner** [comment]
I use an RSA ssh key as well and it can fetch. My quick thought is you might need to enable an ssh-agent.

When you clone the repo fresh are you prompted for a passphrase? Can you `git fetch` and `git push` via command line without getting an additional prompt?

**Comment by robertmircea** [comment]
Unfortunately, even with the agent started still does not work. git fetch and push from command line work without a hitch (with and without agent).

**Comment by rspieldenner** [comment]
Another thought: are your keys the default name `id_dsa/id_dsa.pub` or `id_rsa/id_rsa.pub`?

Which version of the plugin?
Which version of gradle?
jdk version?
git version?

**Comment by nadavc** [comment]
Closing due to inactivity. Please reopen if you encounter this again.

**Comment by theburhan** [comment]
I have tried to use it with local git repository
my remote branch is to the local file system

`git remote -v
local	/Volumes/Secured/local/.git (fetch)
local	/Volumes/Secured/local/.git (push)`

when I run the command
`./gradlew -Prelease.useLastTag=true final`

i get error

```FAILURE: Build failed with an exception.

 What went wrong:
Execution failed for task ':prepare'. 
  Problem fetching from remote.```
